-- SneakPeak MVP Database Schema
-- Matches the live Supabase "Sneak Peak v2" project (nswmbzcllsbpvqtqpitl)
-- Restored from backup — 47 columns in video_results, plus user_ratings table.
--
-- This file is for REFERENCE. The tables already exist in Supabase.
-- Only run this if starting from scratch on a brand-new project.

-- ============================================
-- 1. video_results — core analysis data (47 columns)
-- ============================================
CREATE TABLE IF NOT EXISTS video_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),

    -- Venue info
    venue_name VARCHAR(255) NOT NULL,
    venue_type VARCHAR(100),
    latitude NUMERIC,
    longitude NUMERIC,
    gps_accuracy NUMERIC,
    venue_verified BOOLEAN DEFAULT FALSE,
    venue_distance NUMERIC,
    google_place_id VARCHAR(255),

    -- Audio analysis
    bpm INTEGER,
    volume_level NUMERIC,
    genre VARCHAR(100),
    energy_level VARCHAR(50),
    tempo_consistency NUMERIC,

    -- Visual analysis
    brightness_level NUMERIC,
    lighting_type VARCHAR(100),
    color_scheme VARCHAR(255),
    visual_energy VARCHAR(50),
    lighting_pattern VARCHAR(100),
    color_saturation NUMERIC,
    visual_activity_score NUMERIC,

    -- Crowd analysis
    crowd_density VARCHAR(50),
    activity_level VARCHAR(100),
    density_score NUMERIC,
    estimated_people INTEGER,
    engagement_score NUMERIC,
    movement_patterns VARCHAR(100),

    -- Face / Demographics
    face_count INTEGER DEFAULT 0,
    gender_male_count INTEGER,
    gender_female_count INTEGER,
    gender_male_percentage NUMERIC,
    gender_female_percentage NUMERIC,
    age_average NUMERIC,

    -- Mood
    dominant_mood VARCHAR(100),
    mood_confidence NUMERIC,
    overall_vibe VARCHAR(100),
    joy_percentage NUMERIC,

    -- Privacy
    privacy_protected BOOLEAN DEFAULT FALSE,
    faces_blurred INTEGER,
    blur_quality_score NUMERIC,

    -- Media storage
    video_url TEXT,
    thumbnail_url TEXT,
    video_duration NUMERIC,

    -- Scoring & processing
    energy_score NUMERIC,
    processing_complete BOOLEAN DEFAULT FALSE,
    processing_time INTEGER,

    -- Session / user
    session_id VARCHAR(255),
    user_id UUID
);

-- ============================================
-- 2. user_ratings — community feedback
-- ============================================
CREATE TABLE IF NOT EXISTS user_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_result_id BIGINT REFERENCES video_results(id),
    session_id VARCHAR(255),
    user_id UUID,
    rating INTEGER,
    accuracy_rating INTEGER,
    comment TEXT,
    expected_vibe VARCHAR(100),
    actual_vibe VARCHAR(100),
    would_return BOOLEAN,
    created_at TIMESTAMPTZ DEFAULT now()
);
